version: "1"
rules:
  - base: master
    upstream: jedisct1:master
    autoMerge: true
    autoMergeHardReset: true
  - base: automatic-updates-via-pull-app
    upstream: jedisct1:master
    autoMerge: false
    autoMergeHardReset: false
    assignees:
      - NullVoxPopuli
    reviewers:
      - NullVoxPopuli
label: ":arrow_heading_down: pull"
